config:
  host: devx-helloworld-springboot-tuzk1.nonp-dev-4.use1.eng-nonprod.flexport.internal
  namespace: devx-helloworld-springboot-tuzk1-dev
  image:
    name: artifactory.flexport.io/devx-helloworld-springboot-tuzk1-docker-dev-local/devx-helloworld-springboot-tuzk1
    tag: 0.0.1-SNAPSHOT
